import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import useSWR from 'swr';
import { Doughnut } from 'react-chartjs-2';

import {
	Chart as ChartJS,
	CategoryScale,
	LinearScale,
	BarElement,
	Title,
	ArcElement,
	Tooltip,
	Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';

ChartJS.register(
	CategoryScale,
	LinearScale,
	BarElement,
	Title,
	ArcElement,
	Tooltip,
	Legend
);

export async function getServerSideProps() {
	const res = await fetch('https://www.contrahacker.com/api/example-data');
	const data = await res.json();
	let final = data.data.reduce((acc, curr) => {
		if (acc[curr.sector]) {
			acc[curr.sector] += curr.price;
		} else {
			acc[curr.sector] = curr.price;
		}
		return acc;
	}, {});

	let final1 = data.data.map((ele) => {
		return {
			ticker: ele.ticker,
			price: ele.price,
		};
	});

	const dn = {
    labels: Object.keys(final),
		datasets: [
			{
				label: "count",
				data: Object.values(final),
				backgroundColor: ['orange', 'blue', 'green', 'red'],
				borderWidth: 0,
			},
		],
	};
	const bar = {
		labels: final1.map((ele) => ele.ticker),
		datasets: [
			{
				label: '',
				data: final1.map((ele) => ele.price),
				backgroundColor: ['orange', 'blue', 'green', 'red'],

			},
		],
	};

	return {
		props: {
			data,
			dn,
			bar,
		},
	};
}

const inter = Inter({ subsets: ['latin'] });

// https://www.contrahacker.com/api/example-data

export default function Home({ data, dn, bar }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* {
        data.data?.length === 0 ? (
          <div>Loading...</div>
        ) : (
          data.data.map((ele:any) => (
            <>
              <p>
                {ele.id +"\t"}
                {ele.ticker+"\t" }
                {ele.sector+"\t" }
                {ele.price+"\t" }
              </p>
            </>
          ))
        )
      }
      {data.dataset} */}

      <div className={styles.body}>

			<main className={styles.main}>
				<div className={styles.dn}>
					<Doughnut
						data={dn}
						options={{
              responsive: true,
							plugins: {
                legend:{
                  display:false
                },
								title: {
									display: true,
									text: 'Portfolio Distribution into Sectors',
                  position: 'bottom',
								},
							},
						}}
					/>
				</div>

				<div className={styles.bar}>
					<Bar
						data={bar}
						options={{
              maintainAspectRatio:false,
              responsive: true,
							plugins: {
                legend:{
                  display:false
                },
								title: {
                  display: true,
                  text: 'Price (USD)',
                  position: 'bottom',
								},
							},
						}}
					/>
				</div>
			</main>

      </div>
			{/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
		</>
	);
}
